server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
zuul:
  add-host-header: true #设置为true重定向是会添加host请求头
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  prefix: /proxy #给网关路由添加前缀
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
#hystrix:
  #command: #用于控制HystrixCommand的行为
    #default:
      #execution:
        #isolation:
          #thread:
            #timeoutInMilliseconds: 1000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
#ribbon: #全局配置
  #ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  #ReadTimeout: 3000 #服务请求处理超时时间（毫秒）






